#spring.data.mongodb.uri=mongodb://localhost:27018/workshop_mongo
spring.data.mongodb.uri=mongodb+srv://maria:teste123@google-cloud-webflux-mo.p6g9es0.mongodb.net/?appName=google-cloud-webflux-mongo
spring.data.mongodb.database=workshop_mongo